name: build
on:
  push:
    branches:
      - '*'
    tags:
      - "*"

defaults:
  run:
    shell: bash

env:
  APP_NAME: geogebra-app

jobs:
  build-native-executable:
    name: 'Build native executable'
    if: contains(github.ref, 'tags')
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
            executable_extension: ''
          - os: 'macos-latest'
            label: 'macos'
            executable_extension: ''
          - os: 'windows-latest'
            label: 'windows'
            executable_extension: '.exe'
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: set version env
        run: |
          GITHUB_REF_NAME=${{github.ref_name}}
          echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "set env.RELEASE_VERSION to ${GITHUB_REF_NAME#v}"
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
      - name: check toolchain version
        run: |
          node --version
          npm --version
          rustc --version
          cargo --version
      - name: 'Setup for linux'
        if: matrix.os == 'ubuntu-latest'
        run: |
          # https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts
          # https://askubuntu.com/questions/1252062/how-to-install-libncurses-so-5-in-ubuntu-20-04
          # https://askubuntu.com/questions/522372/installing-32-bit-libraries-on-ubuntu-14-04-lts-64-bit
          # sudo add-apt-repository universe
          sudo dpkg --add-architecture i386 
          sudo apt update
          # install both 32-bit and 64-bit prerequisites of tauri
          # libayatana-appindicator3-dev is the successor of libappindicator3-dev and 64-bit only
          # https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux
          # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
          echo FIX INSTALL FAILED ON GITHUB UBUNTU 22.04 RUNNER
          sudo apt install -y libgcc-s1:i386 libstdc++6:i386 libgdk-pixbuf-2.0-dev:i386 libgdk-pixbuf2.0-dev:i386 libatomic1:i386
          echo install tools for 32-bit support ...
          sudo apt install -y --allow-downgrades \
            gcc-multilib \
            g++-multilib
          echo install 32-bit dependences ...
          sudo apt install -y --allow-downgrades \
            libwebkit2gtk-4.0-dev:i386 \
            libssl-dev:i386 \
            libgtk-3-dev:i386 \
            librsvg2-dev:i386 || echo "install 32-bit dependences failed! Check the logs for details."
          echo install dependences ...
          sudo apt install -y --allow-downgrades \
            libwebkit2gtk-4.0-dev \
            libssl-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libayatana-appindicator3-dev
          echo 'ok'
      - name: 'Setup for macos'
        if: matrix.os == 'macos-latest'
        run: |
          echo 'ok'
      - name: 'Setup for windows'
        if: matrix.os == 'windows-latest'
        run: |
          # choco install visualstudio2019-workload-vctools
          # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019
          echo 'ok'
      - name: Build Native binarys on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "build native binarys..."
          rustup target add x86_64-unknown-linux-gnu
          rustup target add i686-unknown-linux-gnu
          yarn
          yarn tauri info
          yarn tauri build -t x86_64-unknown-linux-gnu
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH
          export PKG_CONFIG_SYSROOT_DIR=/
          yarn tauri build -t i686-unknown-linux-gnu
          echo "build native binarys finished"
      - name: Build Native binarys on macos
        if: matrix.os == 'macos-latest'
        run: |
          echo "build native binarys..."
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          yarn
          yarn tauri info
          yarn tauri build -t x86_64-apple-darwin
          yarn tauri build -t aarch64-apple-darwin
          echo "build native binarys finished"
      - name: Build Native binarys on windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "build native binarys..."
          rustup target add x86_64-pc-windows-msvc
          rustup target add i686-pc-windows-msvc
          yarn
          yarn tauri info
          yarn tauri build -t x86_64-pc-windows-msvc
          yarn tauri build -t i686-pc-windows-msvc || true
          echo "build native binarys finished"
      - name: Display structure of build files
        run: |
          ls -lR src-tauri/target/
      - name: Prepare release files on ${{matrix.label}}
        continue-on-error: true
        if: matrix.os == 'ubuntu-latest'
        run: |
          # for 64-bit binary
          mv src-tauri/target/x86_64-unknown-linux-gnu/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_amd64${{matrix.executable_extension}}
          mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_amd64.AppImage ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_amd64.AppImage
          mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_amd64.deb ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_amd64.deb
          # for 32-bit binary
          mv src-tauri/target/i686-unknown-linux-gnu/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_i386${{matrix.executable_extension}}
          mv src-tauri/target/i686-unknown-linux-gnu/release/bundle/appimage/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_i386.AppImage ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_i386.AppImage
          mv src-tauri/target/i686-unknown-linux-gnu/release/bundle/deb/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_i386.deb ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_i386.deb
      - name: Prepare release files on ${{matrix.label}}
        continue-on-error: true
        if: matrix.os == 'macos-latest'
        run: |
          mv src-tauri/target/x86_64-apple-darwin/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x64${{matrix.executable_extension}}
          mv src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_x64.dmg ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x64.dmg
          7z a -tzip ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x64.app.zip ./src-tauri/target/x86_64-apple-darwin/release/bundle/macos/${{env.APP_NAME}}.app
          mv src-tauri/target/aarch64-apple-darwin/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_aarch64${{matrix.executable_extension}}
          mv src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_aarch64.dmg ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_aarch64.dmg
          7z a -tzip ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_aarch64.app.zip ./src-tauri/target/aarch64-apple-darwin/release/bundle/macos/${{env.APP_NAME}}.app
      - name: Prepare release files on ${{matrix.label}}
        continue-on-error: true
        if: matrix.os == 'windows-latest'
        run: |
          mv src-tauri/target/x86_64-pc-windows-msvc/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x64${{matrix.executable_extension}}
          mv src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_x64_en-US.msi ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x64.msi
          mv src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_x64-setup.exe ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x64-setup.exe
          mv src-tauri/target/i686-pc-windows-msvc/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x86${{matrix.executable_extension}}
          mv src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_x86_en-US.msi ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x86.msi
          mv src-tauri/target/i686-pc-windows-msvc/release/bundle/nsis/${{env.APP_NAME}}_${{env.RELEASE_VERSION}}_x86-setup.exe ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}_x86-setup.exe
      - name: Display structure of build files
        run: |
          ls -l .
      - name: 'Publish binary to release'
        continue-on-error: true
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          file: ${{env.APP_NAME}}-${{matrix.label}}-${{env.RELEASE_VERSION}}*
          tags: true
          draft: false
          overwrite: true